import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //projectsSidebar: [{type: 'autogenerated', dirName: '.'}],

  mainSidebar: [
    // This is the main sidebar for the documentation - related for all projects (like for example authentication)
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['introduction/main', 'introduction/authentication'],
    },
  ],
projectsSidebar: [
  {
    type: 'doc',
    id: 'projects/intro',
    label: 'Projects Introduction'
  },
  {
    type: 'category',
    label: 'Quiz-Application',
    items: [
      'projects/project-quiz/intro',
      {
        type: 'category',
        label: 'Design',
        items: [
          'projects/project-quiz/architecture/main',
          'projects/project-quiz/architecture/architecture',
          'projects/project-quiz/architecture/requirements',
          'projects/project-quiz/architecture/release-design',
          'projects/project-quiz/architecture/full-view'
        ]
      },
      {
        type: 'category',
        label: 'Frontend',
        items: [
          'projects/project-quiz/frontend/main',
        ],
      },
      {
        type: 'category',
        label: 'Backend',
        items: [
          'projects/project-quiz/backend/main',
        ],
      }
    ],
  },
]

};

export default sidebars;
